version: '3.7'

services:
  postgres:
    image: postgis/postgis:12-2.5-alpine
    environment:
      POSTGRES_PASSWORD: change_postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    # this is a relative mount and allows live development
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"

# By default we create named volumes that'll reside in /var/lib/docker/volumes
# If you know what you're doing, you can rm -rf this to start from scratch
volumes:
  pgdata:
