site_name: staysafe
site_description: StaySafe API for detecting Covid-19 Hotspots
repo_url: https://github.com/wadkar/Operations
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/wadkar">wadkar</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
